stages:
  - build
  - deploy

build:
  image: ruby:2.4.1
  stage: build
  before_script:
    - gem install jekyll bundler
    - apt-get update
    - curl -sL https://deb.nodesource.com/setup_7.x | bash -
    - apt-get install -y nodejs
    - npm install -g gulp
    - npm install
  script: gulp
  artifacts:
    paths:
      - dist/

deploy:
  image: python:3.6
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install awscli
  script: AWS_ACCESS_KEY_ID=$AWS_ID_DOCS AWS_SECRET_ACCESS_KEY=$AWS_SECRET_DOCS aws s3 cp --recursive ./dist/ s3://stage.design.imshealth.com/
