image: ruby:2.4.1

before_script:
  - gem install jekyll bundler
  - apt-get update
  - curl -sL https://deb.nodesource.com/setup_7.x | bash -
  - apt-get install -y nodejs python python-pip libpython-dev ca-certificates
  - pip install awscli
  - npm install -g gulp
  - npm install

stages:
  - build
  - deploy

build:
  stage: build
  script: gulp

deploy:
  stage: deploy
  script: AWS_ACCESS_KEY_ID=$AWS_ID_DOCS AWS_SECRET_ACCESS_KEY=$AWS_SECRET_DOCS aws s3 cp --recursive ./dist/ s3://s3.amazonaws.com/stage.design.imshealth.com/
