# Site settings
title: Apollo UI
description: HTML and CSS for the Apollo visual language.
current_version: 1.2.0

# Build settings
source:         docs
destination:    docs-temp
host:           0.0.0.0
port:           4001
baseurl:        ""
# url:
encoding:       UTF-8
# exclude:
# include:
# permalink:
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

collections:
  design:
    output: true
    title: Design
    order: 1
    default_page: downloads.html
  styles:
    output: true
    title: Styles
    order: 2
    default_page: colors.html
  components:
    output: true
    title: Components
    order: 3
    default_page: accordion.html


gitlab_url: https://gitlab.imshealth.com/apollo/apollo-ui
issues_url: https://gitlab.imshealth.com/apollo/apollo-ui/issues

ui_kit:
  web:
    sketch: https://cdn.ims.io/design/drb-downloads/Apollo-Web-v1.1.sketch.zip
    illustrator: https://cdn.ims.io/design/drb-downloads/IMS-Responsive-UI-Kit_Version-1.1.1.5.ai.zip
  ios:
    sketch: https://cdn.ims.io/design/drb-downloads/Apollo-iOS-v1.0.sketch.zip

colors:
  sketch: https://cdn.ims.io/design/drb-downloads/apollo-color-swatches-sketch-1.0.zip
  illustrator: https://cdn.ims.io/design/drb-downloads/apollo-color-swatches-illustrator-1.0.zip

fonts:
  proxima_nova: https://typekit.com/fonts/proxima-nova

icons:
  png: https://cdn.ims.io/design/apollo-icons/apollo-icons-png.zip
  font: https://cdn.ims.io/design/apollo-icons/apollo-icons-font.zip
  svg: https://cdn.ims.io/design/apollo-icons/apollo-icons-svg.zip
  sketch: https://cdn.ims.io/design/apollo-icons/apollo-icons-sketch.zip

cdn:
  css: https://cdn.ims.io/design/css/1.1.1/apollo.css
  css_min: https://cdn.ims.io/design/css/1.1.1/apollo.min.css
  js: https://cdn.ims.io/design/js/1.1.1/apollo.js
  js_min: https://cdn.ims.io/design/js/1.1.1/apollo.min.js
